---
# tasks file for docker
- name: Login DockerHub
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_pass }}"

- name: Pull docker image
  docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
