---
# tasks file for docker
- name: Login DockerHub
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_pass }}"

- name: Start container
  docker_container:
      name: "{{ container_name }}"
      image: "{{ docker_image_name }}:{{ docker_image_tag }}"
      pull: true
      state: "{{ state|default('started') }}"
      restart: yes
      restart_policy: always
      network_mode: host
  